require:
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "Gemfile"
    - "spec/spec_helper.rb"
  NewCops: enable

Layout/LineLength:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false
